Python interpreter path: /bin/python3
Starting Pylance language server.
Error 2021-08-31 01:06:16: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a2235322e3135322e3233382e3138222c2275736572223a22636872697370726f2d31227d/home/chrispro-1/.config/Code/User/settings.json' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a2235322e3135322e3233382e3138222c2275736572223a22636872697370726f2d31227d/home/chrispro-1/.config/Code/User/settings.json')
	at _handleError (/home/chrispro-1/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/out/vs/server/remoteExtensionHostProcess.js:85:158459)
	at async y.readText (/home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.8.1159798656/out/client/extension.js:9:320331)
	at async p.doesFileNeedToBeFixed (/home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.8.1159798656/out/client/extension.js:59:586718)
	at async /home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.8.1159798656/out/client/extension.js:59:585845
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.8.1159798656/out/client/extension.js:59:585791)
	at async p.updateTestSettings (/home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.8.1159798656/out/client/extension.js:59:585418)] {
  code: 'FileNotFound'
}
> conda --version
Error 2021-08-31 01:13:14: Error while running worker[Worker 1]. undefined
Error 2021-08-31 01:13:14: Error while running worker[Worker 2]. undefined
