User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonJoinMailingListVar3'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'pythonDeprecatePythonPath'
User belongs to experiment group 'pythonSortEnvs'
User belongs to experiment group 'pythonRunFailedTestsButtonDisplayed'
User belongs to experiment group 'pythonRefreshTestsButtonDisplayed'
User belongs to experiment group 'pythonRememberDebugConfig'
Starting Pylance language server.
Python interpreter path: /bin/python3
Error 2021-09-12 20:45:55: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a2235322e3138362e37382e3535222c2275736572223a22636872697370726f2d31227d/home/chrispro-1/.config/Code/User/settings.json' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a2235322e3138362e37382e3535222c2275736572223a22636872697370726f2d31227d/home/chrispro-1/.config/Code/User/settings.json')
	at _handleError (/home/chrispro-1/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:94:160087)
	at async y.readText (/home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.9.1218897484/out/client/extension.js:9:314351)
	at async p.doesFileNeedToBeFixed (/home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.9.1218897484/out/client/extension.js:59:823854)
	at async /home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.9.1218897484/out/client/extension.js:59:822981
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.9.1218897484/out/client/extension.js:59:822927)
	at async p.updateTestSettings (/home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.9.1218897484/out/client/extension.js:59:822554)] {
  code: 'FileNotFound'
}
> conda --version
Error 2021-09-12 20:45:57: Error while running worker[Worker 1]. undefined
Error 2021-09-12 20:45:57: Error while running worker[Worker 2]. undefined
